# Retail Orders Analysis - Data cleaning

In [1]:
## import kaggle
! pip install kaggle

Collecting kaggle
  Downloading kaggle-2.2.4-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: bleach in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (4.1.0)
Collecting jupytext (from kaggle)
  Downloading jupytext-1.19.6-py3-none-any.whl.metadata (15 kB)
Collecting kagglesdk<1.0,>=0.1.35 (from kaggle)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (24.1)
Requirement already satisfied: protobuf in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (4.25.3)
Requirement already satisfied: python-dateutil in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (0.21.0)
Requirement already satisfied: python-slugify in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (4.66.5)
Requirement already satisfied: urllib3>=1.15.1 in /opt/anaconda3/lib/python3.12/site-packages (from kaggle) (2.2.3)
Requirement already satisfied: six>=1.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from bleach->kaggle) (1.16.0)
Requirement already satisfied: webencodings in /opt/anaconda3/lib/python3.12/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /opt/anaconda3/lib/python3.12/site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in /opt/anaconda3/lib/python3.12/site-packages (from jupytext->kaggle) (0.3.0)
Requirement already satisfied: nbformat in /opt/anaconda3/lib/python3.12/site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.12/site-packages (from jupytext->kaggle) (6.0.1)
Requirement already satisfied: text-unidecode>=1.3 in /opt/anaconda3/lib/python3.12/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->kaggle) (2025.11.12)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.0)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/anaconda3/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in /opt/anaconda3/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/anaconda3/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in /opt/anaconda3/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.10.6)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (3.10.0)
Downloading kaggle-2.2.4-py3-none-any.whl (126 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Downloading jupytext-1.19.6-py3-none-any.whl (230 kB)
Installing collected packages: kagglesdk, jupytext, kaggle
Successfully installed jupytext-1.19.6 kaggle-2.2.4 kagglesdk-0.1.37

In [2]:
import kaggle

In [3]:
!kaggle --version 
# ! this says that don't treat this as Python code. Run this as a Terminal/shell command.

Kaggle CLI 2.2.4

In [14]:
# download the data set
!kaggle datasets download ankitbansal06/retail-orders

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading retail-orders.zip to /Users/siddharthshreekumar/Desktop/Data Sc_ study/Projects : My work/Portfolio_projects/Retail Order analysis
100%|█████████████████████████████████████████| 200k/200k [00:00<00:00, 217kB/s]

In [15]:
# so its a zip file now we need to extract it
import zipfile
zip_ref = zipfile.ZipFile('retail-orders.zip')
zip_ref.extractall() # extract file to dir
zip_ref.close() # close the file

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# read the csv file
order = pd.read_csv('orders.csv')
order.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [6]:
# lets check the datatype
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   object
 2   Ship Mode         9993 non-null   object
 3   Segment           9994 non-null   object
 4   Country           9994 non-null   object
 5   City              9994 non-null   object
 6   State             9994 non-null   object
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   object
 9   Category          9994 non-null   object
 10  Sub Category      9994 non-null   object
 11  Product Id        9994 non-null   object
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), object(10)
memory usage: 1.2+ MB

In [7]:
# lets see how many null values in each column
order.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           1
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [8]:
order.columns = order.columns.str.lower() # this will make the column names to lower case

In [9]:
# lets cross verify it 
order.head()

,order id,order date,ship mode,segment,country,city,state,postal code,region,category,sub category,product id,cost price,list price,quantity,discount percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [10]:
order.columns

Index(['order id', 'order date', 'ship mode', 'segment', 'country', 'city',
       'state', 'postal code', 'region', 'category', 'sub category',
       'product id', 'cost price', 'list price', 'quantity',
       'discount percent'],
      dtype='object')

In [11]:
# now lets check the data for each column
order['order id'].nunique() # its a pk column

9994

In [12]:
# lets check order_date
order['order date'].dtype # so its object, we need to convert it to datetime

dtype('O')

In [13]:
order['order date'] = pd.to_datetime(order['order date'])

In [14]:
order['order date'] # now its ok

0      2023-03-01
1      2023-08-15
2      2023-01-10
3      2022-06-18
4      2022-07-13
          ...
9989   2023-02-18
9990   2023-03-17
9991   2022-08-07
9992   2022-11-19
9993   2022-07-17
Name: order date, Length: 9994, dtype: datetime64[ns]

In [15]:
# lets check ship mode
order['ship mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [16]:
# now convert the Not Available and unknow to nan
order['ship mode'] = order['ship mode'].replace(['Not Available','unknown'],np.nan)

In [17]:
order['ship mode'].unique() # so we have replaced unknown and Not Available by nan

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [18]:
# also one more thing column names have space , i want to replace by _
order.columns = order.columns.str.replace(' ','_')
order.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [19]:
order.head() # its now ok and easy to access

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [20]:
# now lets see the segment
order['segment'].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

In [21]:
print(order['country'].unique())# now lets see the country
print(order['city'].nunique())# now lets see how many unique cities
print(order['state'].nunique())# now lets see how many unique cities

['United States']
531
49

In [22]:
# lets see the postal code column
print(order['postal_code'].nunique())
print(order['postal_code'].dtype)

631
int64

In [23]:
print(order['region'].unique())
print(order['category'].unique())
print(order['sub_category'].unique())

['South' 'West' 'Central' 'East']
['Furniture' 'Office Supplies' 'Technology']
['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers']

In [24]:
# overall rest columns dtype looks ok and we can proceed further
# so we have cost_price, list_price, quantity, discount_percent

# lets add discount_amount =  list_price * (discount/100)
# lets add net_sale_price = list_price - discount_amount

order['discount_amount'] = order['list_price']*(order['discount_percent']/100)
order['net_sale_price'] = order['list_price'] - order['discount_amount']

In [25]:
order.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount_amount,net_sale_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0

In [26]:
# add a profit column
order['profit'] = order['net_sale_price'] - order['cost_price']

In [27]:
order.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount_amount,net_sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [ ]:
# lets drop some columns which are not required
order.head()
# so we dont need discount_percent as we have amount, so lets drop that only

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount_amount,net_sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [30]:
order.drop(columns = 'discount_percent', inplace=True)

In [32]:
order.head() # check

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_amount,net_sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,1.0,19.0,-1.0

In [34]:
# Now I am using sqlalchemy and mysql
# lets check if pymysql drive was there or not, then install
import sqlalchemy
import pymysql
print('sqlalchemy :',sqlalchemy.__version__)
print('pymysql :',pymysql.__version__) # so this not installed in my system, so lets install this only

ModuleNotFoundError: No module named 'pymysql'

In [35]:
%pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3
Note: you may need to restart the kernel to use updated packages.

In [51]:
# now lets import again
import sqlalchemy
import pymysql
from sqlalchemy import create_engine, text

In [ ]:
print('pymysql :',pymysql.__version__) # ok now its loaded

pymysql : 2.2.8

In [54]:
# lets load data the data .env data and connect 
import os
from dotenv import load_dotenv
env = load_dotenv('.env') # this will load .env file
host = os.getenv("host")
username = os.getenv("username")
password = os.getenv("password")
database = os.getenv("database")
port = os.getenv("port")

try:
    engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
    )
    with engine.connect() as connection:
        result = connection.execute(text("select 1 as 'row', 2 as 'col';"))
        row = result.fetchall()
        print(row)
        print('Connected succesfully')
except Exception as e:
    print(f"Connection issue :{e}")

[(1, 2)]
Connected succesfully

In [57]:
with engine.connect() as connection:
    order.to_sql("order",con = connection,index=False, if_exists='replace')

In [58]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         9994 non-null   int64
 1   order_date       9994 non-null   datetime64[ns]
 2   ship_mode        9988 non-null   object
 3   segment          9994 non-null   object
 4   country          9994 non-null   object
 5   city             9994 non-null   object
 6   state            9994 non-null   object
 7   postal_code      9994 non-null   int64
 8   region           9994 non-null   object
 9   category         9994 non-null   object
 10  sub_category     9994 non-null   object
 11  product_id       9994 non-null   object
 12  cost_price       9994 non-null   int64
 13  list_price       9994 non-null   int64
 14  quantity         9994 non-null   int64
 15  discount_amount  9994 non-null   float64
 16  net_sale_price   9994 non-null   float64
 17  profit           9994 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(5), object(9)
memory usage: 1.4+ MB